# Typografie

## Lettertypes 

### Normaal lettertype

`r paragraph()`

### Cursief lettertype

_`r paragraph()`_

### Vet lettertype

**`r paragraph()`**

### Vet en cursief lettertype

**_`r paragraph()`_**

### Lettertype met vaste tekenbreedte

```{r echo = FALSE, results = "asis"}
cat("`", paragraph(), "`", sep = "")
```

### Beschikbaar aantal karakters

Ongeveer 66 karakters met gewoon lettertype

12345678911234567892123456789312345678941234567895123456789612345678971234567898

_12345678911234567892123456789312345678941234567895123456789612345678971234567898_

**12345678911234567892123456789312345678941234567895123456789612345678971234567898**

**_12345678911234567892123456789312345678941234567895123456789612345678971234567898_**

67 karakters met vaste tekenbreedte

`12345678911234567892123456789312345678941234567895123456789612345678971234567898`

### Kleine letter L versus hoofdletter i

normaal:
  ~ lI

vet:
  ~ **lI**
  
cursief:
  ~ _lI_
  
vet en cursief:
  ~ **_lI_**

met vaste tekenbreedte:
  ~ `lI`

### Speciale karakters

€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789

_€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789_

**€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789**

**_€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789_**

`€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789`

### Aanhalingstekens

normaal:
  ~ "dubbele", 'enkele'

vet:
  ~ **"dubbele", 'enkele'**

cursief:
  ~ _"dubbele", 'enkele'_

vet en cursief:
  ~ **_"dubbele", 'enkele'_**

met vaste tekenbreedte:
  ~ `"dubbele", 'enkele',`

## Opsommingen

### Ongeordende lijsten

- Eerste niveau
- `r sentence(n = 3)` 
- Item 3
    - Tweede niveau
        - Derde niveau
        - Drie niveaus is het maximum
        - `r sentence(n = 3)`
    - `r sentence(n = 3)`
    - Item c
- Item 4

### Ongeordende lijsten incrementeel weergeven

> - Eerste niveau
> - `r sentence(n = 3)`
> - Item 3
>     - Tweede niveau
>         - Derde niveau
>         - Drie niveaus is het maximum
>         - Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. 
>     - Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. 
>     - Item c
> - Item 4

### Genummerde lijsten

1. Eerste niveau
1. `r sentence(n = 3)` 
1. Item 3
    1. Tweede niveau
        1. Derde niveau
        1. Drie niveaus is het maximum
        1. `r sentence(n = 3)` 
    1. `r sentence(n = 3)` 
    1. Item c
1. Item 4

### Genummerde lijsten incrementeel weergeven

> 1. Eerste niveau
> 1. `r sentence(n = 3)` 
> 1. Item 3
>     1. Tweede niveau
>         1. Derde niveau
>         1. Drie niveaus is het maximum
>         1. `r sentence(n = 3)` 
>     1. `r sentence(n = 3)` 
>     1. Item c
> 1. Item 4

### Lijsten met definities

Eerste niveau
  ~ Een definitie van het eerste niveau
  
Een item met een lange titel
  ~ Definitie van het item met lange titel
  
    Tweede niveau
      ~ De definitie van het tweede niveau

        Derde niveau
          ~ Drie niveaus is het maximum

        Een item met een lange titel
          ~ `r sentence(n = 3)` 

    Een item met een lange titel
      ~ `r sentence(n = 3)` 

Item C
  ~ `r sentence(n = 3)` 
  
Item D
  ~ Definitie van D

### Lijsten mengen

- Eerste niveau
- Item 2
- Item 3
    1. Tweede niveau
    
        Derde niveau
          ~ Ook hier maximum drie niveaus
          
        item II
          ~ Uitleg II
          
    1. Item b
        - Item b I
        - Item b II
    1. Item c
        1. Item c I
        1. Item c II
- Item 4

## Kaders

### Standaard kader

(ref:block) `r paragraph()`

```{block2, type = "block", latex.options = "{Titel van het standaardkader}"}
(ref:block)

```

### Kader met voorbeeld
  
(ref:exampleblock) `r paragraph()`
  
```{block2, type = "exampleblock", latex.options = "{Titel van het voorbeeldkader}"}
(ref:exampleblock)

```

### Kader met waarschuwing

(ref:alertblock) `r paragraph()`

```{block2, type = "alertblock", latex.options = "{Titel van het waarschuwingskader}"}
(ref:alertblock)

```
