warning("output file generated by other format will be overwritten")
bookdown::render_book(
  input = "index.Rmd",
  output_format = bookdown::pdf_book(
    base_format = INBOmd::inbo_handouts,
    subtitle = "Optionele ondertitel",
    location = "Hier komt optioneel de plaats",
    institute = "Hier komt optioneel de affiliatie",
    toc_name = "De naam van de inhoudstafel",
    cover = "trees-1036958.jpg",
    cover_horizontal = FALSE,
    slide_level = 3
  )
)
