oldwd <- getwd()
setwd("source/inbo_slides")
warning("output file generated by other format will be overwritten")
bookdown::render_book(
  input = "index.Rmd",
  output_format = bookdown::pdf_book(
    base_format = INBOmd::inbo_rapport_2015,
    subtitle = "Optionele ondertitel"
  )
)
setwd(oldwd)
