warning("output file generated by other format will be overwritten")
bookdown::render_book(
  input = "index.Rmd",
  output_format = bookdown::pdf_book(
    base_format = INBOmd::inbo_rapport,
    subtitle = "Optionele ondertitel"
  )
)
