---
title: "Voorbeeld van referentiestijl"
author: 
  - 
    name: "Thierry Onkelinx & Floris Vanderhaeghe"
    email: "thierry.onkelinx@inbo.be"
link-citations: TRUE
site: bookdown::bookdown_site
bibliography: ../INBOmd.bib
output:
  bookdown::pdf_book:
    base_format: INBOmd::inbo_rapport
    style: INBO
    lof: FALSE
    lot: FALSE
  bookdown::gitbook:
    split_by: "chapter+number"
    template: !expr INBOmd::inbo_rapport_css("html")
    pandoc_args: !expr c("--csl", system.file("inbo.csl", package = "INBOmd"))
  bookdown::epub_book:
    stylesheet: "css/inbo_rapport.css"
    template: !expr INBOmd::inbo_rapport_css("epub")
    pandoc_args: !expr c("--csl", system.file("inbo.csl", package = "INBOmd"))
---

# Verwijzingen in tekst

```{r echo = FALSE, results = "asis"}
library(knitr)
natbib <- any(grepl("natbib", opts_knit$get()$rmarkdown.pandoc.args))
cat(
  sprintf(
    "Stijl referentielijst gebaseerd op %s.\n\n", 
    ifelse(natbib, "bst", "csl")
  )
)
```

Table: Verschillende types documenten

| BibTex type   | voorbeelden                                                  |
| ------------- | ------------------------------------------------------------ |
| Article       | [@article-single; @article-double; @article-triple] |
| Book          | [@book-a1e0; @book-a2e0; @book-a3e0; @book-a0e1; @book-a0e2; @book-a0e3; @BanerjeeEtal2003] |
| Booklet       | [@booklet-a0; @booklet-a1; @booklet-a2; @booklet-a3] |
| Conference    | [@conference-a1e1; @conference-a2e0; @conference-a3e3] |
| InBook        | [@inbook-a1e0; @inbook-a0e1; @inbook-a2e0; @inbook-a3e0] |
| InCollection  | [@incollection-a1e1; @incollection-a2e0; @incollection-a3e3] |
| InProceedings | [@inproceedings-a3e3; @inproceedings-a2e1; @inproceedings-a1e0; @Onkelinx2014a] |
| Manual        | [@manual-a3; @manual-a2; @manual-a1; @manual-a0] |
| MastersThesis | [@masterthesis] |
| Misc          | [@misc] |
| Misc (with type set as dataset)   | [@onkelinx_thierry_2019_2682323; @oosterlynck_patrik_2019_3550995] |
| Online (a BibLaTeX type) | [@databank_ondergrond_vlaanderen_bepalen_nodate; @european_topic_centre_on_biological_diversity_etc/bd_reference_2016; @wikipedia_muizenberg_2019;@lastnameWebpageTitle2020] |
| PhdThesis     | [@phdthesis] |
| Proceedings   | [@proceedings-e0; @proceedings-e1; @proceedings-e2; @proceedings-e3] |
| TechReport    | [@techreport-a1; @techreport-a2; @techreport-a3] |
| Unpublished   | [@unpublished-a3; @unpublished-a2; @unpublished-a1] |


Table: Weergave van namen

| Bibtex                            | Weergave \hphantom{aaaaaaaaaaaaaaaaaa}|
| --------------------------------- | ------------------------------------- |
| Achternaam                        | @name0   |
| Achternaam, Voornaam              | @name1   |
| De Achternaam, V.                 | @name2   |
| Van de Achternaam, V              | @name3   |
| Achternaam, Voornaam Tweede       | @name4   |
| Achternaam, Voornaam Tweede Derde | @name5   |
| Achternaam, V. T. D.              | @name6   |
| Achternaam, VTD                   | @name7   |
| Achternaam, Voornaam TD           | @name8   |
| Accent áâàäçéêëèíuîïìóôöòúûüù     | @name9   |

## DOI of URL

- beide: @article-single
- enkel DOI: @Amano2012
- enkel URL: @franklin_mapping_2009

# Na te kijken

Algemene opvolging gebeurt in [deze gsheet](https://docs.google.com/spreadsheets/d/1cQfMKcVxCiGOH6s2np-uecRa-5_r1vS2MGRpqLGM2Gk).

## Op te volgen voor bst

Specifieke zaken (zie ook gsheet):

- Conference
  - `Organization` beter laten vallen in bst en dit veld niet ondersteunen? citeproc-js toont het niet en pandoc-citeproc voegt dit vooraan in het publisher-veld gevolgd door ";" en publisher (dit gebeurt nog vóór de CSL-processing, dus bij omzetting bib-file).
- Laten vallen van “URL:” en “DOI:” prefixen.
- Zoals in csl: Nederlandstalige variant voorzien voor verschillende termen, o.a.: ed. (nl) ipv edn. (en) en Nr. (nl) ipv No. (en).
- Aanpassing van 'Vol. van', 'No. in' naar de afgesproken syntaxis (zie gsheet).
- Bij ontbreken van de datum: gebruik '(s.d.)' (cf. csl)
  - zie voorbeeld @databank_ondergrond_vlaanderen_bepalen_nodate.
- Hanteer `<title>. <edition>` in plaats van	`<title>, <edition>`.
  - Reden: 'title' betreft soms meerdere delen, gescheiden door een punt (bv. titel. subtitel). Het laatste deel laten volgen door een komma en dan '2nd edn.' is wat raar. Zie bv. @book-a1e0.
  - NB. voor InBook wordt de voorgestelde werkwijze al gevolgd in bst.
- Voor het BibLaTeX type '**Online**' (aangewezen voor een webpage, want enkel dan wordt dit correct vertaald door pandoc en Zotero als een webpage): volgen van de csl weergave
  - weergave van `[WWW document]` na de titel
  - toevoegen van "(accessed `datum als tekst`). In csl gebeurt dit taal-afhankelijk, bv. (accessed June 30, 2020) versus (geraadpleegd 30 juni 2020).
  - merk op dat `@online` een BibLaTeX type is. Om een bib-file met dit type zonder probleem in te kunnen lezen in **JabRef**, moet je bij de preferences > advanced kiezen voor de _BibLaTeX mode_!
  

## Issues in het csl bestand

Betreft `research-institute-for-nature-and-forest.csl`.

Momenteel zijn geen resterende issues gekend in de ontwikkelversie.

Issues kunnen gepost worden op de INBO-fork van de CSL-repository (<https://github.com/inbo/styles>), waar verbeteringen aan de file gebeuren (om dan bij te dragen aan de CSL-repo zelf).

### Aandachtspunten bij aanmaken van een bib bestand

Er zijn wel enkele aandachtspunten in verband met het gebruik van een bib-file in combinatie met CSL, meer bepaald in verband met de wijze van ingeven van bepaalde velden.
Deze worden behandeld in hoofdstuk \@ref(bibcsl).

Merk op dat deze aandachtspunten overbodig zijn indien de invoer gebeurt via Zotero en vandaaruit een bib-bestand wordt geëxporteerd, dit met de [Better BibTeX plugin](https://retorque.re/zotero-better-bibtex/) geïnstalleerd.
    
## Bijzonderheden in de Zotero addon 'Better BibTeX'

Bijzonderheden bij import/export van `INBOmd.bib` naar/van Zotero met addon 'Better BibTeX'

### Export van article met page-range 'x-y'

Range `x-y` wordt omgezet naar `x--y` (in bib-file).

Zie bespreking in het [issue](https://github.com/retorquere/zotero-better-bibtex/issues/1602).
Dit blijkt een weloverwogen feature te zijn (en geen bug) om met zekerheid n-dashes te induceren voor page-ranges.
Zie ook: '[many, but not all, BibTeX styles will correct hyphen to n-dash](https://tex.stackexchange.com/a/58671/27603)'.




