# Dankwoord {-}

\lipsum[69-74]

# Voorwoord {-}

\lipsum[75-79]

# Samenvatting {-}

\lipsum[80-84]

# Aanbevelingen voor beheer en/of beleid {-}

\lipsum[85-89]

# Abstract {-}

\benglish

\lipsum[89-93]

\eenglish

\mainmatter

# Inleiding 

Het doel van dit document is louter de beschikbare stijlelementen te tonen. De pdf versie geeft als doelstelling een drukklare versie van een tweezijdig rapport af te leveren. De titelpagina's van het rapport en van de verschillende delen staan steeds op de rechterpagina. Het eerste hoofdstuk van een rapport of van een deel begint eveneens steeds op de rechterpagina. Hierdoor komt er onvermijdelijk een blanco pagina tussen een titelpagina en het eerste hoofdstuk. 

## Lipsum

Lorem ipsum is een opvultekst die drukkers, zetters, grafisch ontwerpers en dergelijken gebruiken om te kijken hoe een lay-out er grafisch uitziet.

De reden waarom de tekst gebruikt worden door die doelgroep is dat bij een leesbare tekst de lezer afgeleid zou worden door de inhoud, terwijl het alleen om de vormgeving gaat. Bovendien heeft het Lorem ipsum een redelijk normale afwisseling van de verschillende letters en korte en lange woorden.

Wanneer we een korte zin nodig hebben gebruiken we "Filmquiz bracht knappe ex-yogi
van de wijs." Deze zin heeft als voordeel dat alle letters van het alfabet er in voorkomen.

In de broncode van dit document vind je stukjes code als `\usepackage{lipsum}` of `\lipsum[10]`. Deze code is enkel nodig om de stukjes van de Lipsum tekst te tonen. In een werkelijk rapport heb je deze uiteraard niet nodig.
