# Dankwoord {-}

\lipsum[69-73] Filmquiz bracht knappe ex-yogi van de wijs.

# Voorwoord {-}

\lipsum[75-79] Filmquiz bracht knappe ex-yogi van de wijs.

# Samenvatting {-}

Een uittreksel over ecologie uit [Wikipedia](https://nl.wikipedia.org/wiki/Ecologie)

Ecologie (ook wel met de spelling: _oecologie_) als wetenschap is een onderdeel van biologie. De ecologie bestudeert de dynamiek van de wisselwerking tussen organismen, populaties of levensgemeenschappen (de biotische milieufactoren) en de relaties tussen organismen, populaties, levensgemeenschappen of landschappen en het niet-biologische milieu (de abiotische milieufactoren). De studie op het niveau van de soort heet ook wel autoecologie en op het niveau van de levensgemeenschap en ecosysteem heet gemeenschapsecologie of synecologie.

Het woord ecologie (oorspronkelijk Duits: _Ökologie_) werd geïntroduceerd door de Duitse bioloog Ernst Haeckel in 1866, als samentrekking van de Griekse woorden _oikos_ (huishouding) en _logos_ (studie, wetenschap).

In de Angelsaksische wereld werd dit _ecology_, dat daar een iets andere, meer milieukundige en mens-gerichte, betekenis kreeg. In Nederland bestaan het meer biologische oecologie en meer milieukundige ecologie naast elkaar, maar het verschil vervaagt.

Het woord ecologie wordt ook gebruikt in andere betekenissen:

- gerelateerd aan een beter milieu, in het bijzonder dat van de mens, 
- meer praktisch, betreffende gedrag dat goed is voor de mens en zijn milieu en voor de natuur (zie [ecologische landbouw](https://nl.wikipedia.org/wiki/Ecologische_landbouw) en [EKO-keurmerk](https://nl.wikipedia.org/wiki/EKO-keurmerk)), 
- gericht op een bepaalde levensbeschouwing (zie [ecologisme](https://nl.wikipedia.org/wiki/Ecologisme)).
- betreffende omgeving of netwerk van bijvoorbeeld een bedrijf.

# Aanbevelingen voor beheer en/of beleid {-}

\lipsum[85-89] Filmquiz bracht knappe ex-yogi van de wijs.

# English abstract {-}

\benglish

Excerpt on ecology taken from [Wikipedia](https://en.wikipedia.org/wiki/Ecology)

**Ecology** (from οίκος, "house", or "environment"; -λογία, "study of") is the branch of [biology](http://www.dictionary.com/browse/ecology|title=the definition of ecology|website=Dictionary.com|access-date=2018-02-20) which studies the interactions among organisms and their environment. Objects of study include interactions of organisms with each other and with abiotic components of their environment. Topics of interest include the biodiversity, distribution, biomass, and opulations of organisms, as well as cooperation and competition within and between species Ecosystems are dynamically interacting systems of organisms, the communities they make up, and the non-living components of their environment. Ecosystem processes, such as primary production, pedogenesis, nutrient cycling, and niche construction, regulate the flux of energy and matter through an environment. These processes are sustained by organisms with specific life history traits. Biodiversity means the varieties of species, genes, and ecosystems, enhances certain ecosystem services.

Ecology is not synonymous with environmentalism, natural history, or environmental science. It overlaps with the closely related sciences of evolutionary biology, genetics, and ethology. An important focus for ecologists is to improve the understanding of how biodiversity affects ecological function. Ecologists seek to explain:

* Life processes, interactions, and adaptations
* The movement of materials and energy through living communities
* The successional development of ecosystems
* The abundance and distribution of organisms and biodiversity in the context of the environment.

Ecology has practical applications in conservation biology, wetland management, natural resource management (agroecology, agriculture, forestry, agroforestry, fisheries), city planning (urban ecology), community health, economics, basic and applied science, and human social interaction (human ecology). For example, the _Circles of Sustainability_ approach treats ecology as more than the environment 'out there'. It is not treated as separate from humans. Organisms (including humans) and resources compose ecosystems which, in turn, maintain biophysical feedback mechanisms that moderate processes  acting on living (biotic) and non-living (abiotic) components of the planet. Ecosystems sustain life-supporting functions and produce natural capital like  biomass production (food, fuel, fiber, and medicine), the regulation of climate, global biogeochemical cycles, water filtration, soil formation, erosion control, flood protection, and many other natural features of scientific, historical, economic, or intrinsic value.

The word "ecology" ("Ökologie") was coined in 1866 by the German scientist Ernst Haeckel. Ecological thought is derivative of established currents in philosophy, particularly from ethics and politics [@LaferriereStoett1999]. Ancient Greek philosophers such as Hippocrates and Aristotle laid the foundations of ecology in their studies on natural history. Modern ecology became a much more rigorous science in the late 19th century. Evolutionary concepts relating to adaptation and natural selection became the cornerstones of modern ecological theory.

\eenglish

\mainmatter

# Inleiding 

Het doel van dit document is louter de beschikbare stijlelementen te tonen. De pdf versie heeft als doelstelling een drukklare versie van een tweezijdig rapport af te leveren. De titelpagina's van het rapport en van de verschillende delen staan steeds op de rechterpagina. Het eerste hoofdstuk van een rapport of van een deel begint eveneens steeds op de rechterpagina. Hierdoor komt er een blanco pagina tussen een titelpagina en het eerste hoofdstuk. 

## Lipsum

Lorem ipsum is een opvultekst die drukkers, zetters, grafisch ontwerpers en dergelijke gebruiken om te kijken hoe een lay-out er uit ziet.

De reden waarom de tekst gebruikt wordt door die doelgroep is dat bij een leesbare tekst de lezer afgeleid zou worden door de inhoud, terwijl het alleen om de vormgeving gaat. Bovendien heeft het Lorem ipsum een redelijk normale afwisseling van de verschillende letters en korte en lange woorden.

Wanneer we een korte zin nodig hebben gebruiken we "Filmquiz bracht knappe ex-yogi
van de wijs." Deze zin heeft als voordeel dat alle letters van het alfabet er in voorkomen.

In de broncode van dit document vind je stukjes code als `\usepackage{lipsum}` of `\lipsum[10]`. Deze code is enkel nodig om de stukjes van de Lipsum tekst te tonen. In een werkelijk rapport heb je deze uiteraard niet nodig.
