# (PART) Typografie {-}

# Definitie van typografie

In dit hoofdstuk geven we de definities van de huisstijl van de ontwerpstijl in Word en de Markdown versie. Wanneer de Markdown versie afwijkt van de Word versie geven we de afwijkende cijfers in het vet weer.

## Marges

Maat | Word | Markdown
---- | ---- | --------
boven | 20 mm | 20 mm
binnenkant | 30 mm | 30 mm
onder | 25 mm | 25 mm
buitenkant | 30 mm | 30 mm
koptekst | 25 mm vanaf bovenkant blad | niet gedefinieerd
voettekst | 15 mm vanaf onderkant blad |  **10 mm van onderkant tekst**

## Basisparagraaf

Maat | Word | Markdown
---- | ---- | --------
kleur | zwart | zwart
lettertype | Calibri | Calibri
fontsize | 9 pt | 9pt
gewicht | normaal | normaal
inspringen | 0 mm | 0 mm
uitlijnen | links | links
witruimte voor | 0 pt | 0 pt
witruimte na | 9 pt | 9 pt
regelafstand | 1.15 | 1.15

### Verwijzingen

#### Intern

Maat | Word | Markdown
---- | ---- | --------
kleur | blauw | blauw

#### URL

Maat | Word | Markdown
---- | ---- | --------
kleur | blauw | blauw

#### Citatie

Maat | Word | Markdown
---- | ---- | --------
kleur | zwart | blauw

## Koppen

Enkel de afwijkingen t.o.v. de basisparagraaf worden weergegeven

### Deel

Maat | Word | Markdown
---- | ---- | --------
kleur | - | **fuchsia**
fontsize | - | **28 pt**
gewicht | - | **vet small caps**
regelafstand |  | **32.2pt**

### Kop 1

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
fontsize | 18 pt | 18 pt
gewicht | vet all caps | vet all caps
inspringen | verkeerd om 7.6 mm | verkeerd om 7.6mm
witruimte voor | 24 pt | 24 pt^[start steeds op een nieuwe pagina]
witruimte na | 24 pt | 24pt
regelafstand | 21.6 pt | 21.6pt

### Kop 1 zonder nummering

Het betreft de titels van voorwoord, samenvatting, inhoudstafel, ...

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
fontsize | 14 pt | 14pt
gewicht | vet | vet
witruimte na | 14 pt | 14pt
regelafstand | 30 pt | 30 pt

### Kop 2

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
fontsize | 16 pt | 16pt
gewicht | all caps | all caps
onderstreept | stippellijn | stippellijn
inspringen | verkeerd om 15 mm | verkeerd om 15 mm
witruimte voor | 10 pt | 10 pt
witruimte na | 12 pt | 12pt
regelafstand | 20 pt | 20pt

### Kop 3

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
fontsize | 12 pt | 12pt
gewicht | vet | vet
inspringen | verkeerd om 15 mm | verkeerd om 15 mm
witruimte voor | 10 pt | 10 pt

### Kop 4

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
gewicht | vet | vet
inspringen | verkeerd om 15 mm | verkeerd om 15 mm
witruimte voor | 10 pt | 10pt

### Kop 5

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
inspringen | verkeerd om 17.8 mm | verkeerd om 17.8 mm
witruimte na | 9 pt | 9pt

### Kop 6

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
inspringen | verkeerd om 20.3 mm | verkeerd om 20.3 mm
witruimte na | 9 pt | 9pt

## Voettekst

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
fontsize | 8 pt | 8 pt
paginanummers | vet | vet
paginanummers | buitenkant | buitenkant
DOI | gecenteerd | gecentreerd
www.inbo.be | binnenkant | binnenkant

## Cover

In Markdown wordt de verticale indeling van de coverpagina als volgt bepaalt.

1. Plaats bovenaan het verticale Nederlandstalige INBO logo 17 mm hoog.
1. Plaats de titel
1. Plaats 60 pt verticale witruimte
1. Plaats de (optionele) ondertitel
1. Plaats 30 pt vertical witruimte
1. Plaats de auteurs
1. Plaats 144 pt verticale witruimte
1. Plaats de DOI en het (optionele) opdrachtnummer
1. Verdeel de overblijvende verticale ruimte in twee. Plaats de ene helft tussen het logo en de titel. De andere helft komt onderaan de pagina.

### Titel

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
font | Flanders art Sans | **Calibri** (optioneel Flanders art Sans)
fontsize | 18 pt | 18pt
gewicht | vet all caps | vet all caps
tekenafstand | 0.25 pt verbreed | 0.25 pt verbreed
onderstreept | volle lijn | volle lijn
links inspringen | 10 mm | 10 mm
witruimte voor | 21 pt | 21pt
witruimte na | 26 pt | 26pt
regelafstand | 60 pt | 60 pt

### Ondertitel

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
fontsize | 18 pt | 18 pt
gewicht | vet | vet
links inspringen | 10 mm | 10 mm
regelafstand | 30 pt | 30 pt

### Auteurs

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
fontsize | 12 pt | 12 pt
links inspringen | 10 mm | 10 mm
witruimte voor | 12 pt | 12 pt
witruimte na | 144 pt | 144 pt

### DOI + opdrachtnummer

Maat | Word | Markdown
---- | ---- | --------
kleur | fuchsia | fuchsia
links inspringen | 10 mm | 10 mm
witruimte na | 0 pt | 0 pt

## Inhoudstafel

In Markdown wordt enkel t.e.m. kop 3 in de inhoudstafel weergegeven.

Maat | Word | Markdown
---- | ---- | --------
paginanummer | zwart | **blauw**^[om aan te geven dat het een klikbare link is]

### Deel 1

Maat | Word | Markdown
---- | ---- | --------
font size | - | **11pt**
gewicht | | **vet**
witruimte voor | - | **6pt**

### Kop 1

Maat | Word | Markdown
---- | ---- | --------
font size | 11 pt | 11pt
witruimte voor | 3 pt wanneer niet identiek | **3pt** altijd
witruimte na | 3 pt wanneer niet identiek | **0pt** altijd
links inspringen | verkeerd om 15 mm | verkeerd om 15 mm

### Kop 2

Maat | Word | Markdown
---- | ---- | --------
witruimte voor | 3 pt wanneer niet identiek | **0pt** altijd
witruimte na | 3 pt wanneer niet identiek | **0pt** altijd
links inspringen | verkeerd om 15 mm | verkeerd om 15 mm

### Kop 3

Maat | Word | Markdown
---- | ---- | --------
witruimte voor | 3 pt wanneer niet identiek | **0pt** altijd
witruimte na | 3 pt wanneer niet identiek | **0pt** altijd
links inspringen | verkeerd om 15 mm | verkeerd om 15 mm

# Kopstijlen: niveau 1: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. {#h:koppen}

\lipsum[1-3] Filmquiz bracht knappe ex-yogi van de wijs.

## Niveau 2: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs.

\lipsum[4-6] Filmquiz bracht knappe ex-yogi van de wijs.

### Niveau 3: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs.

\lipsum[7-10] Filmquiz bracht knappe ex-yogi van de wijs.

#### Niveau 4: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs.

\lipsum[10-12] Filmquiz bracht knappe ex-yogi van de wijs.

##### Niveau 5: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs.

\lipsum[13-15] Filmquiz bracht knappe ex-yogi van de wijs.

###### Niveau 6: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs.

\lipsum[16-18] Filmquiz bracht knappe ex-yogi van de wijs.

# Kopstijlen zonder nummer: niveau 1: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. {- #h:koppen-zonder-nummer}

\lipsum[19] Filmquiz bracht knappe ex-yogi van de wijs.

## Niveau 2: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. {-}

\lipsum[20] Filmquiz bracht knappe ex-yogi van de wijs.

### Niveau 3: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. {-}

\lipsum[21] Filmquiz bracht knappe ex-yogi van de wijs.

#### Niveau 4: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. {-}

\lipsum[22-23] Filmquiz bracht knappe ex-yogi van de wijs.

##### Niveau 5: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. {-}

\lipsum[24] Filmquiz bracht knappe ex-yogi van de wijs.

###### Niveau 6: Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. Filmquiz bracht knappe ex-yogi van de wijs. {-}

\lipsum[25] Filmquiz bracht knappe ex-yogi van de wijs.

# Lettertypes

## Normaal

\lipsum[26] Filmquiz bracht knappe ex-yogi van de wijs.

## Vet

**\lipsum[27] Filmquiz bracht knappe ex-yogi van de wijs.**

## Cursief

_\lipsum[28] Filmquiz bracht knappe ex-yogi van de wijs._

## Vet en cursief

_**\lipsum[29] Filmquiz bracht knappe ex-yogi van de wijs.**_

## Met vaste tekenbreedte

\texttt{\lipsum[30] Filmquiz bracht knappe ex-yogi van de wijs.}

`Filmquiz bracht knappe ex-yogi van de wijs.`

**`Filmquiz bracht knappe ex-yogi van de wijs.`**

**`Filmquiz`** `bracht knappe ex-yogi van de` **`wijs`**.

80 karakters passen in de breedte

`12345678911234567892123456789312345678941234567895123456789612345678971234567898`

**`12345678911234567892123456789312345678941234567895123456789612345678971234567898`**

100 karakters passen niet meer in de breedte

`1234567891123456789212345678931234567894123456789512345678961234567897123456789812345678991234567890`

**`1234567891123456789212345678931234567894123456789512345678961234567897123456789812345678991234567890`**

## Kleine letter L versus hoofdletter i

normaal:
  ~ lI

vet:
  ~ **lI**
  
cursief:
  ~ _lI_

vet en cursief:
  ~ **_lI_**

met vaste tekenbreedte:
  ~ `lI` **`lI`**

## Grote letter O versus cijfer 0

normaal:
  ~ O0

vet:
  ~ **O0**
  
cursief:
  ~ _O0_

vet en cursief:
  ~ **_O0_**

met vaste tekenbreedte:
  ~ `O0` **`O0`**

## Speciale characters
  
### Normaal

€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789

### Vet
**€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789**

### Cursief
_€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789_

### Vet en cursief
**_€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789_**
  
### Met vaste tekenbreedte
`€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789`

**`€$£ @&#§µ^ ()[]{}|²³<>/\*+- ,;:.?!~ äàáâã ëèéê ïìíî öòóô üùúû ÿ ç ñ ÄÀÁÂ ËÈÉÊ ÏÌÍÎ ÖÒÓÔ ÜÙÚÛ Ñ 0123456789`**

## Aanhalingstekens

normaal:
  ~ "dubbele", 'enkele'

vet:
  ~ **"dubbele", 'enkele'**

cursief:
  ~ _"dubbele", 'enkele'_

vet en cursief:
  ~ **_"dubbele", 'enkele'_**

met vaste tekenbreedte:
  ~ `"dubbele", 'enkele',` **`"dubbele", 'enkele',`**

# Opsommingen

## Ongeordende lijsten

- \lipsum[31] Filmquiz bracht knappe ex-yogi van de wijs.
- Item 2
- Item 3
    - Item a
        - item I
        - item II
            - item A
            - item B
            - \lipsum[32] Filmquiz bracht knappe ex-yogi van de wijs.
        - \lipsum[33] Filmquiz bracht knappe ex-yogi van de wijs.
    - \lipsum[34] Filmquiz bracht knappe ex-yogi van de wijs.
    - Item c
- Item 4

## Genummerde lijsten

1. \lipsum[35] Filmquiz bracht knappe ex-yogi van de wijs.
1. Item 2
1. Item 3
    1. Item a
        1. item I
        1. item II
            1. \lipsum[36] Filmquiz bracht knappe ex-yogi van de wijs.
            1. item B
            1. item C
        1. \lipsum[37] Filmquiz bracht knappe ex-yogi van de wijs.
    1. \lipsum[38] Filmquiz bracht knappe ex-yogi van de wijs.
    1. Item c
1. Item 4

## Lijsten met definities

Item A
  ~ \lipsum[39] Filmquiz bracht knappe ex-yogi van de wijs.
  
Longer item title B
  ~ \lipsum[40] Filmquiz bracht knappe ex-yogi van de wijs.
  
    Item B1
      ~ \lipsum[41] Filmquiz bracht knappe ex-yogi van de wijs.

        Item B1a
          ~ \lipsum[42] Filmquiz bracht knappe ex-yogi van de wijs.

        Item B1b
          ~ \lipsum[43] Filmquiz bracht knappe ex-yogi van de wijs.

            Item B1b1
              ~ \lipsum[44] Filmquiz bracht knappe ex-yogi van de wijs.
              
    Item B2
      ~ \lipsum[45] Filmquiz bracht knappe ex-yogi van de wijs.

Item C
  ~ \lipsum[46] Filmquiz bracht knappe ex-yogi van de wijs.
  
Item D
  ~ \lipsum[47] Filmquiz bracht knappe ex-yogi van de wijs.

## Lijsten mengen

- Item 1
- Item 2
- Item 3
    1. Item a
    
        item I
          ~ Uitleg I
          
        item II
          ~ Uitleg II
          
    1. Item b
        - Item b I
        - Item b II
    1. Item c
        1. Item c I
        1. Item c II
- Item 4


# Kaders

\lipsum[48] Filmquiz bracht knappe ex-yogi van de wijs.

## Standaard kader

```{block2, type = "block"}
\lipsum[49] Filmquiz bracht knappe ex-yogi van de wijs.
```

\lipsum[50-51] Filmquiz bracht knappe ex-yogi van de wijs.

```{block2, type = "block", latex.options = "{Optionele titel van het kader}"}
\lipsum[52-53] Filmquiz bracht knappe ex-yogi van de wijs.
```

## Kader met voorbeeld
  
\lipsum[54] Filmquiz bracht knappe ex-yogi van de wijs.

```{block2, type = "exampleblock"}
\lipsum[55] Filmquiz bracht knappe ex-yogi van de wijs.
```

\lipsum[56-58] Filmquiz bracht knappe ex-yogi van de wijs.

```{block2, type = "exampleblock", latex.options = "{Optionele titel van het kader}"}
\lipsum[59-60] Filmquiz bracht knappe ex-yogi van de wijs.
```

## Kader met waarschuwing

\lipsum[61] Filmquiz bracht knappe ex-yogi van de wijs.

```{block2, type = "alertblock"}
\lipsum[62] Filmquiz bracht knappe ex-yogi van de wijs.
```

\lipsum[63] Filmquiz bracht knappe ex-yogi van de wijs.

```{block2, type = "alertblock", latex.options = "{Optionele titel van het kader}"}
\lipsum[64-65] Filmquiz bracht knappe ex-yogi van de wijs.
```

\lipsum[66] Filmquiz bracht knappe ex-yogi van de wijs.

```{block2, type = "alertblock"}
\lipsum[67-68] Filmquiz bracht knappe ex-yogi van de wijs.
```
