---
title: "Voorbeelden met INBOmd"
author: "Thierry Onkelinx"
css: '`r sprintf("inbo_rapport/libs/INBOmd-%s/report.css", packageVersion("INBOmd"))`'
output: 
  html_document:
    self_contained: FALSE
---

Op deze website vind je de gerenderde voorbeelden van [inbomd_examples](https://github.com/inbo/inbomd_examples).

- basis INBO rapport ([broncode](https://github.com/inbo/inbomd_examples/tree/master/source/inbo_rapport))
    - [PDF](inbo_rapport/inbo_rapport.pdf) versie
    - [HTML](inbo_rapport/index.html) versie
    - [EPUB](inbo_rapport/inbo_rapport.epub) versie
- alternatief INBO rapport ([broncode](https://github.com/inbo/inbomd_examples/tree/master/source/inbo_rapport_delen))
    - extra's
        - delen (groepeert hoofdstukken)
    - verschillen
        - citaties zijn niet klikbaar
        - geen lijst met figuren (enkel bij pdf)
        - geen lijst met tabellen (enkel bij pdf)
        - zwevende elementen zijn niet beperkt tot hun sectie (enkel bij pdf)
    - [PDF](inbo_rapport_delen/inbo_rapport_delen.pdf) versie
    - [HTML](inbo_rapport_delen/index.html) versie
    - [EPUB](inbo_rapport_delen/inbo_rapport_delen.epub) versie
- Nederlandstalig rapport in de huisstijl van de Vlaamse overheid ([broncode](https://github.com/inbo/inbomd_examples/tree/master/source/vlaanderen_rapport))
    - [PDF](vlaanderen_rapport/vlaanderen_rapport.pdf) versie
- Engelstalig rapport in de huisstijl van de Vlaamse overheid ([broncode](https://github.com/inbo/inbomd_examples/tree/master/source/flanders_report))
    - [PDF](flanders_report/flanders_report.pdf) versie
- INBO presentatie ([broncode](https://github.com/inbo/inbomd_examples/tree/master/source/inbo_slides))
    - [Stapsgewijze](inbo_slides/inbo_slides.pdf) slides in pdf
    - [Handout versie](inbo_slides/inbo_slides_handout.pdf) slides in pdf
    - [Rapport versie](inbo_slides/inbo_slides_rapport.pdf) in pdf
- Presentatie in overkoepelende huisstijl Vlaamse overheid ([broncode](https://github.com/inbo/inbomd_examples/tree/master/source/flanders_slides))
    - [Stapsgewijze](flanders_slides/flanders_slides.pdf) slides in pdf
    - [Handout versie](flanders_slides/flanders_slides_handout.pdf) slides in pdf
    - [Rapport versie](flanders_slides/flanders_slides_rapport.pdf) in pdf
- Voorbeelden van referenties ([broncode](https://github.com/inbo/inbomd_examples/tree/master/source/citation_style))
    - [PDF met Nederlandstalige bibliografie](citation_style/nl/citation_style.pdf)
    - [HTML met Nederlandstalige bibliografie](citation_style/nl/index.html)
    - [PDF met Engelstalige bibliografie](citation_style/en/citation_style.pdf)
    - [HTML met Engelstalige bibliografie](citation_style/en/index.html)
