on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-inbomd-examples
jobs:
  test-examples:
    runs-on: ubuntu-latest
    name: "test Rmd"
    steps:
      - uses: actions/checkout@v3
      - uses: inbo/actions/render_inbomd@main
