on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-inbomd-examples
jobs:
  test-examples:
    runs-on: ubuntu-latest
    name: "test Rmd"
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: inbo/actions/render_inbomd@devel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
